secret-key: ${JWT_SECRET_KEY}
aes-key: ${AES_SECRET_KEY}

server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  mail:
    host: ${MAIL_SENDER_HOST}
    port: ${MAIL_SENDER_PORT}
    username: ${MAIL_SENDER_USERNAME}
    password: ${MAIL_SENDER_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: ${MAIL_SENDER_HOST}
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: root
    password:

  h2:
    console:
      enabled: true

  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    open-in-view: true
  sql:
    init:
      mode: always
      data-locations: classpath:test/data.sql
